
export const ADD_STATUS = "ADD_STATUS"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const ADD_TAG = "ADD_TAG"
export const BLOG_DETAILS = "BLOG_DETAILS"
export const UPDATE_BLOG_DETAILS = "UPDATE_BLOG_DETAILS"
export const PREVIEW_BLOG = "PREVIEW_BLOG"
export const SET_ALL_CATEGORIES = "SET_ALL_CATEGORIES"
export const SET_ALL_SUB_CATEGORIES = "SET_ALL_SUB_CATEGORIES"